// This file, generated by XDR Compiler for C++ version 1.0.2221. Release: Jul 22 2009. 15:57:02.

#ifndef __XDR_RoomServerInteralMessage__
#define __XDR_RoomServerInteralMessage__

#include <XDR/XDR.h>

#ifndef __XDR_MESSAGE_InternalMessage_UserOnClose_108287866__
#define __XDR_MESSAGE_InternalMessage_UserOnClose_108287866__
class InternalMessage_UserOnClose : public XDR::IMessage
{
public:
    enum {tagMsgID = 108287866};

protected:
    bool bSubMessageFlag;
    int32 nMsgID;

public:
    InternalMessage_UserOnClose(void) : bSubMessageFlag(false), nMsgID(tagMsgID)
    {
    }
    virtual ~InternalMessage_UserOnClose(void)
    {
    }

    virtual void Clear(void)
    {
    }
    virtual int32 GetID(void) const
    {
        return tagMsgID;
    }
    virtual const char *GetName(void) const
    {
        return "InternalMessage_UserOnClose";
    }
    virtual int32 GetLength(void)
    {
        int32 nLength = 0;

#if (_MSC_VER >= 1301) || defined(_UNIX_)
        if (bSubMessageFlag == false)
        {
            nLength += XDR::EncodingRules::GetLength(&nMsgID);
        }
#elif (_MSC_VER >= 1200)
        // Visual C++ 6.0
        if (bSubMessageFlag == false)
        {
            nLength += XDR::EncodingRules::GetLength(&nMsgID);
        }
#endif

        return nLength;
    }
    virtual bool Save(XStream::THandle hStream)
    {
#if (_MSC_VER >= 1301) || defined(_UNIX_)
        if (bSubMessageFlag == false)
        {
            if (XDR::EncodingRules::Save(hStream, &nMsgID) == false)
            {
                return false;
            }
        }
#elif (_MSC_VER >= 1200)
        // Visual C++ 6.0
        if (bSubMessageFlag == false)
        {
            if (XDR::EncodingRules::Save(hStream, &nMsgID) == false)
            {
                return false;
            }
        }
#endif

        return true;
    }
    virtual bool Load(XStream::THandle hStream)
    {
#if (_MSC_VER >= 1301) || defined(_UNIX_)
        if (bSubMessageFlag == false)
        {
            if (XDR::EncodingRules::Load(hStream, &nMsgID) == false)
            {
                return false;
            }
        }
#elif (_MSC_VER >= 1200)
        // Visual C++ 6.0
        if (bSubMessageFlag == false)
        {
            if (XDR::EncodingRules::Load(hStream, &nMsgID) == false)
            {
                return false;
            }
        }
#endif
        return true;
    }
    virtual void SetSubMessageFlag(bool bSubMessageFlag)
    {
        this->bSubMessageFlag = bSubMessageFlag;
    }
    virtual bool GetSubMessageFlag(void) const
    {
        return bSubMessageFlag;
    }
};
#endif // __XDR_MESSAGE_InternalMessage_UserOnClose_108287866__

#endif
